-- TCAEvent OS Cockpit — Supabase migration
-- Run once in the Supabase SQL editor for the nerd-nite project

-- 1. Extend show_state with cockpit columns
ALTER TABLE show_state
  ADD COLUMN IF NOT EXISTS current_state      text NOT NULL DEFAULT 'pre_show',
  ADD COLUMN IF NOT EXISTS state_entered_at   timestamptz;

-- 2. Checklist completions
CREATE TABLE IF NOT EXISTS show_checklist (
  id          bigint generated by default as identity primary key,
  edition     text NOT NULL,
  state_id    text NOT NULL,
  item_key    text NOT NULL,
  completed   boolean NOT NULL DEFAULT false,
  updated_at  timestamptz DEFAULT now(),
  UNIQUE(edition, state_id, item_key)
);

ALTER TABLE show_checklist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon read checklist"  ON show_checklist FOR SELECT TO anon USING (true);
CREATE POLICY "anon write checklist" ON show_checklist FOR ALL    TO anon USING (true) WITH CHECK (true);

-- 3. Boss-to-boss comms
CREATE TABLE IF NOT EXISTS show_comms (
  id          bigint generated by default as identity primary key,
  edition     text NOT NULL,
  sender      text NOT NULL,
  message     text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE show_comms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon read comms"  ON show_comms FOR SELECT TO anon USING (true);
CREATE POLICY "anon write comms" ON show_comms FOR INSERT TO anon WITH CHECK (true);

-- 4. Enable realtime for new tables
ALTER PUBLICATION supabase_realtime ADD TABLE show_checklist;
ALTER PUBLICATION supabase_realtime ADD TABLE show_comms;
